name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - run: pip install build
      - run: python -m build --sdist --wheel
      - uses: pypa/gh-action-pypi-publish@v1
        with:
          password: '${{ secrets.PYPI_TOKEN }}'
